substitutions:
  device_name: "wyswietlacz_paper"

# Core
esphome:
  name: "${device_name}"
  platform: ESP8266
  board: esp01_1m

# WiFi
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid_iot
    password: !secret wifi_password
  ap:
    ssid: ${device_name}
    password: !secret wifi_password


# Captive portal
captive_portal:

# Enable logging
logger:
  level: VERY_VERBOSE

# API
api:

# OTA
ota:
  password: !secret ota_password

# Switch
switch:
  - platform: restart
    name: "${device_name} Restart"

# Text Sensors
text_sensor:
  - platform: wifi_info
    ip_address:
      name: '${device_name} IP Address'
      icon: mdi:ip

# Web server
web_server:
  port: 80
  auth:
    username: pawel
    password: !secret ota_password

# Time
time:
  - platform: homeassistant
    id: homeassistant_time

#Please edit your homeassistant sensors enitity id to match yours
sensor:
  - platform: wifi_signal
    name: '${device_name} WiFi Signal'
    id: wifisignal
    update_interval: 60s